export const LOADING = 'LOADING'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNOUT = 'SIGNOUT'
export const SET_MODE = 'SET_MODE'

export const GET_BLOG = 'GET_BLOG'
export const GET_PROJECT_CATEGORY = 'GET_PROJECT_CATEGORY'

export const GET_ALL_PROJECT = 'GET_ALL_PROJECT_DETAIL'
export const GET_USER = 'GET_USER'

export const GET_TASK_TYPE = 'GET_TASK_TYPE'
export const GET_PRIORITY = 'GET_PRIORITY'

export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL'

export const GET_TASK_DETAIL = 'GET_TASK_DETAIL'

export const ADD_USER_PROJECT = 'ADD_USER_PROJECT'

export const NOTI_SNACK = 'NOTI_SNACK'

export const NAVIGATE = 'NAVIGATE'

export const OPEN_MODAL = 'OPEN_MODAL'

export const CLOSE_MODAL = 'CLOSE_MODAL'

export const GET_ALL_USER = 'GET_ALL_USER'

export const ASSIGN = 'ASSIGN'

export const OPEN_MODAL_EDIT_TASK = 'OPEN_MODAL_EDIT_TASK'

export const CLOSE_MODAL_EDIT_TASK = 'CLOSE_MODAL_EDIT_TASK'

export const OPEN_MODAL_TASK_DETAIL = 'OPEN_MODAL_TASK_DETAIL'

export const CLOSE_MODAL_TASK_DETAIL = 'CLOSE_MODAL_TASK_DETAIL'
